[project]
name = "full-transformer-implementation"
version = "0.1.0"
description = "Attention is All You Need paper Implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "datasets",
    "tokenizers",
    "torchmetrics",
    "tqdm",
    "tensorboard",
]
